name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
    - name: Verify CUE schemas
      run: cue vet schemas.cue
    - name: Export CUE schemas
      run: |-
        cue export --force schemas.cue -e hamster -o hamster.json --out json
        cue export --force schemas.cue -e cat -o cat.json --out json
        cue export --force schemas.cue -e dog -o dog.json --out json
        cue export --force schemas.cue -e owl -o owl.json --out json
        cue export --force schemas.cue -e monkey -o monkey.json --out json
